scene.onOverlapTile(SpriteKind.Player, assets.tile`tile4`, function (sprite, location) {
    startnextlevel()
})
function startnextlevel () {
    for (let value of sprites.allOfKind(SpriteKind.Enemy)) {
        value.destroy()
    }
    currentlevel += 1
    if (currentlevel == 1) {
        tiles.setTilemap(tilemap`platformer1`)
    } else if (currentlevel == 2) {
        tiles.setTilemap(tilemap`level02`)
    } else {
        game.over(true)
    }
    scene.cameraFollowSprite(mySprite)
    tiles.placeOnRandomTile(mySprite, assets.tile`tile3`)
    info.setLife(3)
    for (let value of tiles.getTilesByType(assets.tile`tile5`)) {
        myenemy = sprites.create(img`
            ........................
            ........................
            ........................
            ........................
            .........fffff..........
            ........f11111ff........
            .......fb111111bf.......
            .......f1111111dbf......
            ......fd111111dddf......
            ......fd11111ddddf......
            ......fd11dddddddf......
            ......f111dddddddf......
            ......f11fcddddddf......
            .....fb1111bdddbf.......
            .....f1b1bdfcfff........
            .....fbfbffffffff.......
            ......fffffffffff.ff....
            ...........ffffffff.....
            ........f1b1bffffff.....
            ........fbfbffffff......
            ........................
            ........................
            ........................
            ........................
            `, SpriteKind.Enemy)
        tiles.placeOnTile(myenemy, tiles.getTileLocation(0, 0))
        myenemy.follow(mySprite, 30)
    }
}
controller.A.onEvent(ControllerButtonEvent.Pressed, function () {
    mySprite.vy = -200
})
scene.onOverlapTile(SpriteKind.Player, assets.tile`tile2`, function (sprite, location) {
    game.over(false)
})
sprites.onOverlap(SpriteKind.Player, SpriteKind.Enemy, function (sprite, otherSprite) {
    let othersprite: Sprite = null
    otherSprite.destroy()
    if (mySprite.x < othersprite.x) {
        sprite.vy = -100
    } else {
        info.changeLifeBy(-1)
    }
})
let myenemy: Sprite = null
let currentlevel = 0
let mySprite: Sprite = null
scene.setBackgroundColor(11)
mySprite = sprites.create(assets.image`myImages.image0`, SpriteKind.Player)
mySprite.ay = 500
controller.moveSprite(mySprite, 100, 0)
startnextlevel()
